### ISSUE TITLE
Download blockcerts 

### ISSUE THREAD

**Issue by sdimodica** [blockchain-certificates/blockcerts-verifier#32]
Hi, 
I read "allow-download: (Boolean. default: false). Enables the download of the record. At this moment only records provided by Learning Machine are downloadable.".

What's the reason? I'd like to use it with all certificates in blockchain.

Thank you.

**Comment by lemoustachiste** [comment]
Hi @sdimodica,

The reason for this is that we developed the code with the Learning Machine use-case in mind. 
It is not set in stone and we would accept PRs for other cases. The download code is here: https://github.com/blockchain-certificates/blockcerts-verifier/blob/master/src/domain/certificates/useCases/download.js#L3

As you can see, in our case we add a `?format=json` to a certificate URL to allow for actual download. But we didn't want to impose this standard on everyone, which is why we chose a whitelist approach.

**Comment by sdimodica** [comment]
Hi @lemoustachiste ,
in our use case we're going to define a domain for each issuer so we can't list all the enabled domains.
We add a `?format=json` to the certificate URL in order to download the JSON too.
What about dropping that "if" checking the domain name? Do you see any drawbacks on dropping it?

**Comment by AnthonyRonning** [comment]
@lemoustachiste, and we do the same that @sdimodica describes below. I verified for our custom URL's, downloading is not enabled. We should probably remove this whitelist and document the `?format=json` parameter.

**Comment by lemoustachiste** [comment]
I agree

**Comment by sdimodica** [comment]
OK, great! Can I proceed with a PR?

**Comment by lemoustachiste** [comment]
Please do

**Comment by sdimodica** [comment]
Hi,
this is the related PR: https://github.com/blockchain-certificates/blockcerts-verifier/pull/39
