### ISSUE TITLE
shared-styles access through node package

### ISSUE THREAD

**Issue by fabcom-aaron** [blockchain-certificates/blockcerts-verifier#711]
I've been trying to workout how to implement my own shared-styles. The src folder is ignored by npm so there is no way to access any of those files of add any of my own. Can someone provide an example of how I can make use of share-styles to add css before the credential display html due to the fact that the sanitizer takes out anything associated with styling.

**Comment by lemoustachiste** [comment]
Hi @fabcom-aaron,

sorry I just saw this issue. At this moment styling of documents should occur at the credentials level in the `displayHTML` property. Most rules indeed are sanitized but we are managing to get decent styles nonetheless. 

If you'd want to customize the verifier, at this point there aren't many options. Since we are also working with webcomponents, styles are encapsulated and not accessible from the outer page. In that case the only option I see for you is to fork the component. That way you could also play with the sanitizer to enable more rules, but beware if you cannot trust the source of what's being verified as this opens the door to XSS attacks

**Comment by fabcom-aaron** [comment]
Been working through this, one weird issue I need clarification on is element id attributes. Are these removed from the displayHTML by the sanitizer?
